server:
  port: 9527
eureka:
  instance:
    hostname: cloud-gateway-serivce
  client:
    service-url:
      #表示是否将自己注册进EurekaServer默认为true
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7002.com:7002eureka/

spring:
  application:
    name: cloud-gateway
